Food/urls.py
from django.urls import path
from .views import *
from . import views

app_name = 'food'

urlpatterns = [
    path('<str:slug>/', FoodDetailView.as_view(), name='food_detail'),
    path('', FoodListView.as_view(), name='menu'),
    path('bua-sang', FoodBreakfastListView.as_view(), name='bua-sang'),
    path('bua-trua', FoodLunchListView.as_view(), name='bua-trua'),
    path('bua-toi', FoodDinnerListView.as_view(), name='bua-toi'),
    path('do-uong', FoodBeverageListView.as_view(), name='do-uong'),
    path('an-vat', FoodSnackListView.as_view(), name='an-vat'),
]

cantin_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('users/', include('django.contrib.auth.urls')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('articles/', include('articles.urls', namespace='articles')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('menu/', include('Food.urls', namespace='food')),
    path('', include('pages.urls')),
]

cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:food_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:food_id>/', views.cart_remove, name='cart_remove'),
]

orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'
urlpatterns = [
    path('create/', views.order_create, name='order_create'),
]

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms

FOOD_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]

class CartAddFoodForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=FOOD_QUANTITY_CHOICES, coerce=int)
    override = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from Food.models import Food
from .cart import Cart
from .forms import CartAddFoodForm

@require_POST
def cart_add(request, food_id):
    cart = Cart(request)
    food = get_object_or_404(Food, id=food_id)
    form = CartAddFoodForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(food=food,
                quantity=cd['quantity'],
                override_quantity=cd['override'])
    return redirect('cart:cart_detail')

@require_POST
def cart_add_2(request, food_id):
    cart = Cart(request)
    food = get_object_or_404(Food, id=food_id)
    form = CartAddFoodForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(food=food,
                quantity=cd['quantity'],
                override_quantity=cd['override'])
    return redirect(request.META.get('HTTP_REFERER'))
    

@require_POST
def cart_remove(request, food_id):
    cart = Cart(request)
    food = get_object_or_404(Food, id=food_id)
    cart.remove(food)
    return redirect('cart:cart_detail')

def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddFoodForm(initial={
            'quantity': item['quantity'],
            'override': True})
    return render(request, 'cart/detail.html', {'cart': cart})

templates/cart/detail.html
{% extends "new_base.html" %}

{% load static %}

{% load humanize %}

{% block title %}
    Your shopping cart
{% endblock %}
{% block content %}
    <h1>Giỏ hàng của bạn</h1>
    
    <table class="table">
        <thead class="thead-dark">
            <tr>
                <th>Hình ảnh</th>
                <th>Sản phẩm</th>
                <th>Số lượng</th>
                <th>Loại bỏ</th>
                <th>Đơn giá</th>
                <th>Thành tiền</th>
            </tr>
        </thead>
        <tbody>
            {% with total_items=cart|length %}
                {% if total_items == 0 %}
                    <tr><td>Giỏ hàng của bạn đang trống</td></tr>
                {% else %}
                    {% for item in cart %}
                        {% with product=item.food %}
                            <tr>
                                <td>
                                    <a href="{{ product.get_absolute_url }}">
                                        <img class="img-thumbnail" width=200 height=200 src="{% static product.img.url|slice:"6:" %}">
                                    </a>
                                </td>
                                <td>{{ product.food_name }}</td>
                                <td>
                                    <form action="{% url "cart:cart_add" product.id %}" method="post">
                                        {{ item.update_quantity_form.quantity }}
                                        {{ item.update_quantity_form.override }}
                                        <input type="submit" value="Update">
                                        {% csrf_token %}
                                    </form>
                                </td>
                                <td>
                                    <form action="{% url "cart:cart_remove" product.id %}" method="post">
                                        <input type="submit" value="Remove">
                                        {% csrf_token %}
                                    </form>
                                </td>
                                <td class="num">{{ item.price|floatformat|intcomma }} vnđ</td>
                                <td class="num">{{ item.total_price|floatformat|intcomma }} vnđ</td>
                            </tr>
                        {% endwith %}
                    {% endfor %}
                {% endif %}
            {% endwith %}
            <tr class="table-success">
                <td>Tổng</td>
                <td colspan="4"></td>
                <td class="num">{{ cart.get_total_price|floatformat|intcomma }} vnđ</td>
            </tr>
        </tbody>
    </table>
    <p class="text-ri   ght">
        <a href="{{request.META.HTTP_REFERER}}" class="btn btn-info ml-auto">Tiếp tục mua</a>
        <a href="{% url "orders:order_create" %}" class="btn btn-success float-right">Thanh toán ></a>
    </p>
{% endblock %}