Food/urls.py
from django.urls import path
from .views import *
from . import views

app_name = 'food'

urlpatterns = [
    path('<str:slug>/', FoodDetailView.as_view(), name='food_detail'),
    path('', FoodListView.as_view(), name='menu'),
    path('bua-sang', FoodBreakfastListView.as_view(), name='bua-sang'),
    path('bua-trua', FoodLunchListView.as_view(), name='bua-trua'),
    path('bua-toi', FoodDinnerListView.as_view(), name='bua-toi'),
    path('do-uong', FoodBeverageListView.as_view(), name='do-uong'),
    path('an-vat', FoodSnackListView.as_view(), name='an-vat'),
]

articles/urls.py
from django.urls import path
from .views import ArticleListView, ArticleDetailView

app_name='articles'

urlpatterns = [
    path('<str:slug>/', ArticleDetailView.as_view(), name='detail'),
    path('', ArticleListView.as_view(), name='list'),

]

cantin_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('users/', include('django.contrib.auth.urls')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('articles/', include('articles.urls', namespace='articles')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('menu/', include('Food.urls', namespace='food')),
    path('', include('pages.urls')),
]

cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:food_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:food_id>/', views.cart_remove, name='cart_remove'),
]

Food/models.py
from django.db import models
from django.urls import reverse
from django.utils.text import slugify

# Create your models here.

class Food(models.Model):

    BREAKFAST = 'BR'
    LUNCH = 'LU'
    DINNER = 'DI'
    BEVERAGE = 'BE'
    SNACK = 'SN'

    Food_Type_Choice = [
        (BREAKFAST, 'Bữa sáng'),
        (LUNCH, 'Bữa trưa'),
        (DINNER, 'Bữa tối'),
        (BEVERAGE, 'Đồ uống'),
        (SNACK, 'Ăn vặt'),
    ]

    food_name = models.CharField(max_length=100)
    food_type = models.CharField(max_length=2, choices=Food_Type_Choice, default=SNACK)
    description = models.TextField()
    price = models.FloatField(default=0)
    discount = models.FloatField(default=0)
    img = models.ImageField(upload_to='static/images/foods')
    slug = models.SlugField(unique=True, blank=True, null=True)

    def save(self, *args, **kwargs):
        self.slug = slugify((str(self.id) + " " + self.food_name))
        super(Food, self).save(*args, **kwargs)

    def __str__(self):
        return self.food_name

    def get_absolute_url(self):
        return reverse('food:food_detail', args=[self.slug])
    

templates/about.html
{% extends 'new_base.html' %}

{% load static %}

{% block title %}Giới thiệu{% endblock title%}

{% block content %}

<div class=container>

    <h1>Căn tin uit</h1>
    <p>Địa chỉ: Căn tin UIT khu phố 6, phường Linh Trung, quận Thủ Đức</p>
    <p>Hotline <a href="tel:+08123456123">08 123456 123</a></p>
    <p>Chúng tôi rất hân hạnh được phục vụ</p>
    <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3918.2323517551895!2d106.80235905085983!3d10.869924260394102!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3175272d1f9968a7%3A0x4193ad334c5913b9!2zQ8SDbiB0aW4gVUlUIChOaMOgIHBo4bulYyB24bulIHNpbmggdmnDqm4uKQ!5e0!3m2!1svi!2s!4v1594924216149!5m2!1svi!2s" width="600" height="450" frameborder="0" style="border:0;" allowfullscreen="" aria-hidden="false" tabindex="0"></iframe>
</div>

{% endblock content %}

templates/article_detail.html
{% extends 'new_base.html' %}

{% load static %}

{% block content %}
    <div class="container">
        <h1>{{ object.title }}</h1>
            
            <p>at {{ object.date }}</p>
            <img src="{% static article.photo.url|slice:"6:" %}" class="img-thumbnail" alt="Card image cap" width="700" height="700">
            <p>{{ object.content }}</p>
            <a href="{% url "articles:list" %}" class="btn btn-warning ml-auto"> < Quay lại</a>
    </div>


{% endblock content %}

templates/article_list.html
{% extends 'new_base.html' %}

{% load static %}

{% block title %}Articles{% endblock title %}
{% block content %}

    <div class="container" style="padding-top:50px">
        <h1 style="text-align:center"> Tin tức & các chương trình khuyến mãi HOT </h1>

        <div class="card-deck">
            {% for article in articles_list %}
            <div class="card" >
                <img class="card-img-top" width="345" height="180" src="{% static article.photo.url|slice:"6:" %}" alt="Card image cap">
                <div class="card-body">
                    <h5 class="card-title"><a href="{% url 'articles:detail' article.slug %}">{{ article.title }}</a></h5>
                    <p class="card-text">{{ article.content }}</p>
                </div>
            </div>
            {% endfor %}
        </div>

        <a href="{% url "home" %}" class="btn btn-warning ml-auto"> < Quay lại trang chủ</a>
    </div>

    
    </div>
        
{% endblock content %}

templates/contact.html
{% extends 'new_base.html' %}

{% load static %}

{% block title %}Liên hệ{% endblock title%}

{% block content %}

<div class="container contact-form">
            <div class="contact-image">
                <img src="{% static 'images/feedback.png' %}" alt="rocket_contact" style="display: block; margin-left: auto; margin-right: auto; width: 50%"/>
            </div>
            <form method="post">
                <h3>Hãy liên hệ với chúng tôi qua hotline <a href="tel:+08123456123">08 123456 123</a></h3>
                <h3>Hoặc địa chỉ: Căn tin UIT khu phố 6, phường Linh Trung, quận Thủ Đức</h3>
                <h3>Hoặc điền vào form dưới đây, chúng tôi lắng nghe mọi ý kiến từ bạn!</h3>
               <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <input type="text" name="txtName" class="form-control" placeholder="Họ tên *" value="" />
                        </div>
                        <div class="form-group">
                            <input type="text" name="txtEmail" class="form-control" placeholder="Email *" value="" />
                        </div>
                        <div class="form-group">
                            <input type="text" name="txtPhone" class="form-control" placeholder="Số điện thoại *" value="" />
                        </div>
                        <div class="form-group">
                            <input type="submit" name="btnSubmit" class="btnContact" value="Gửi" />
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <textarea name="txtMsg" class="form-control" placeholder="Nội dung *" style="width: 100%; height: 150px;"></textarea>
                        </div>
                    </div>
                </div>
            </form>
</div>

{% endblock content %}

templates/custom_food_list.html
{% extends 'new_base.html' %}

{% load static %}

{% load humanize %}

{% block title %}Menu{% endblock title %}

{% block content %}
<section class="popular">
            <div class="container">
                <div class="food">
                    <div class="title text-xs-center m-b-30">
                        <h2>Ăn gì hôm nay?</h2>
                        <p class="lead">Hãy chọn món ăn yêu thích của bạn và đặt hàng ngay</p>
                    </div>
                    <div class="row">
                        {% for food in food_list %}
                                <div class="col-xs-12 col-sm-6 col-md-4 food-item">
                                    <div class="food-item-wrap">
                                        <div class="figure-wrap bg-image" data-image-src="{% static food.img.url|slice:"6:" %}"></div>
                                        <div class="content">
                                            <h5><a href="{{ food.get_absolute_url }}">{{food.food_name}}</a></h5>
                                            <div class="product-name">{{food.description}}</div>
                                            <div class="price-btn-block">
                                                <span class="price">{{ food.price|floatformat|intcomma }} vnđ</span>
                                                <form action="{% url "cart:cart_add" food.id %}" method="post">
                                                    {{ cart_product_form }}
                                                    {% csrf_token %}
                                                    <input type="submit" value="Thêm vào giỏ" class="btn theme-btn-dash pull-right">
                                                </form>
                                            </div>
                                        </div>											
                                    </div>
                                </div>
                        {% endfor %}
                    </div>
                </div>
                <a href="{% url "home" %}" class="btn btn-warning ml-auto"> < Quay lại</a>
            </div>
        </section>
{% endblock content %}

templates/food_detail.html
{% extends 'new_base.html' %}

{% load static %}

{% load humanize %}

{% block title %} {{ object.food_name}} {% endblock title %}

{% block content %}
    <div class="container">
        <br>
        <a href="{% url "food:menu" %}" class="btn btn-warning ml-auto"> < Quay lại</a>
        <!-- item info -->
        <h1 class="my-4">{{ object.food_name }}</h1>

        <div class="row">

            <div class="col-md-8">
                <img class="img-fluid" src="{% static food.img.url|slice:"6:" %}" alt="">
            </div>

            <div class="col-md-4">
                <h3 class="my-3">{{ object.food_name }}</h3>
                <h3 class="my-3">{{ object.price|floatformat|intcomma }} vnd</h3>
                <form action="{% url "cart:cart_add" object.id %}" method="post">
                    {{ cart_product_form }}
                    {% csrf_token %}
                    <input type="submit" value="Thêm vào giỏ" class="btn btn-warning">
                </form>
            </div>
        </div>
        <h1 class = "my-4">Thông tin sản phẩm</h1>
        <p>{{ object.description }}</p>

        <!-- related -->

        <h3 class="my-4">Các món ăn khác bạn có thể thích</h3>

        <div class="row">
            {% for food in food_list %}
                <div class="col-md-3 col-sm-6 mb-4">
                    <a href="#">
                        <img class="img-fluid" width="500" height="500" src="{% static food.img.url|slice:"6:" %}" alt="">
                        <h2 class="my-4">{{ food.food_name }}</h1>
                        <small>{{ food.price|floatformat|intcomma }} vnd</small>
                    </a>
                </div>
            {% endfor %}

        </div>


    </div>
{% endblock %}

templates/food_list.html
{% extends 'new_base.html' %}

{% load static %}

{% load humanize %}

{% block title %}Menu{% endblock title %}

{% block content %}
<section class="popular">
            <div class="container">
                <div class="breakfast-menu">
                    <div class="title text-xs-center m-b-30">
                        <h2>Ăn gì sáng hôm nay?</h2>
                        <p class="lead">Hãy chọn món ăn yêu thích của bạn và đặt hàng ngay</p>
                    </div>
                    <div class="row">
                        {% for food in breakfast_list %}
                            <div class="col-xs-12 col-sm-6 col-md-4 food-item">
                                <div class="food-item-wrap">
                                    <div class="figure-wrap bg-image" data-image-src="{% static food.img.url|slice:"6:" %}"></div>
                                    <div class="content">
                                        <h5><a href="{{ food.get_absolute_url }}">{{food.food_name}}</a></h5>
                                        <div class="product-name">{{food.description}}</div>
                                        <div class="price-btn-block">
                                            <span class="price">{{ food.price|floatformat|intcomma }} vnđ</span>
                                            <form action="{% url "cart:cart_add" food.id %}" method="post">
                                                {{ cart_product_form }}
                                                {% csrf_token %}
                                                <input type="submit" value="Thêm vào giỏ" class="btn theme-btn-dash pull-right">
                                            </form>
                                        </div>
                                    </div>											
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                </div>

                <div class="breakfast-menu">
                    <div class="title text-xs-center m-b-30">
                        <h2>Ăn gì trưa hôm nay?</h2>
                        <p class="lead">Hãy chọn món ăn yêu thích của bạn và đặt hàng ngay</p>
                    </div>
                    <div class="row">
                        {% for food in lunch_list %}
                            <div class="col-xs-12 col-sm-6 col-md-4 food-item">
                                <div class="food-item-wrap">
                                    <div class="figure-wrap bg-image" data-image-src="{% static food.img.url|slice:"6:" %}"></div>
                                    <div class="content">
                                        <h5><a href="{{ food.get_absolute_url }}">{{food.food_name}}</a></h5>
                                        <div class="product-name">{{food.description}}</div>
                                        <div class="price-btn-block">
                                            <span class="price">{{ food.price|floatformat|intcomma }} vnđ</span>
                                            <form action="{% url "cart:cart_add" food.id %}" method="post">
                                                {{ cart_product_form }}
                                                {% csrf_token %}
                                                <input type="submit" value="Thêm vào giỏ" class="btn theme-btn-dash pull-right">
                                            </form>
                                        </div>
                                    </div>											
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                </div>

                <div class="breakfast-menu">
                    <div class="title text-xs-center m-b-30">
                        <h2>Ăn gì tối hôm nay?</h2>
                        <p class="lead">Hãy chọn món ăn yêu thích của bạn và đặt hàng ngay</p>
                    </div>
                    <div class="row">
                        {% for food in dinner_list %}
                            <div class="col-xs-12 col-sm-6 col-md-4 food-item">
                                <div class="food-item-wrap">
                                    <div class="figure-wrap bg-image" data-image-src="{% static food.img.url|slice:"6:" %}"></div>
                                    <div class="content">
                                        <h5><a href="{{ food.get_absolute_url }}">{{food.food_name}}</a></h5>
                                        <div class="product-name">{{food.description}}</div>
                                        <div class="price-btn-block">
                                            <span class="price">{{ food.price|floatformat|intcomma }} vnđ</span>
                                            <form action="{% url "cart:cart_add" food.id %}" method="post">
                                                {{ cart_product_form }}
                                                {% csrf_token %}
                                                <input type="submit" value="Thêm vào giỏ" class="btn theme-btn-dash pull-right">
                                            </form>
                                        </div>
                                    </div>											
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                </div>

                <div class="breakfast-menu">
                    <div class="title text-xs-center m-b-30">
                        <h2>Ăn vặt gì hôm nay?</h2>
                        <p class="lead">Hãy chọn món ăn yêu thích của bạn và đặt hàng ngay</p>
                    </div>
                    <div class="row">
                        {% for food in snack_list %}
                            <div class="col-xs-12 col-sm-6 col-md-4 food-item">
                                <div class="food-item-wrap">
                                    <div class="figure-wrap bg-image" data-image-src="{% static food.img.url|slice:"6:" %}"></div>
                                    <div class="content">
                                        <h5><a href="{{ food.get_absolute_url }}">{{food.food_name}}</a></h5>
                                        <div class="product-name">{{food.description}}</div>
                                        <div class="price-btn-block">
                                            <span class="price">{{ food.price|floatformat|intcomma }} vnđ</span>
                                            <form action="{% url "cart:cart_add" food.id %}" method="post">
                                                {{ cart_product_form }}
                                                {% csrf_token %}
                                                <input type="submit" value="Thêm vào giỏ" class="btn theme-btn-dash pull-right">
                                            </form>
                                        </div>
                                    </div>											
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                </div>

                <div class="beverage">
                    <div class="title text-xs-center m-b-30">
                        <h2>Uống gì hôm nay?</h2>
                        <p class="lead">Hãy chọn cho mình thức uống yêu thích và đặt ngay</p>
                    </div>
                    <div class="row">
                        {% for food in food_list %}
                            {% if food.food_type == 'BE' %}
                                <div class="col-xs-12 col-sm-6 col-md-4 food-item">
                                    <div class="food-item-wrap">
                                        <div class="figure-wrap bg-image" data-image-src="{% static food.img.url|slice:"6:" %}"></div>
                                        <div class="content">
                                            <h5><a href="{{ product.get_absolute_url }}">{{food.food_name}}</a></h5>
                                            <div class="product-name">{{food.description}}</div>
                                            <div class="price-btn-block">
                                                <span class="price">{{ food.price|floatformat|intcomma }} vnđ</span>
                                                <form action="{% url "cart:cart_add" food.id %}" method="post">
                                                    {{ cart_product_form }}
                                                    {% csrf_token %}
                                                    <input type="submit" value="Thêm vào giỏ" class="btn theme-btn-dash pull-right">
                                                </form>
                                            </div>
                                        </div>											
                                    </div>
                                </div>
                            {% endif %}
                        {% endfor %}
                    </div>
                </div>
            </div>
        </section>
{% endblock content %}

templates/new_base.html
{% load static %}
{% load humanize %}

<!DOCTYPE html>

<html lang=en>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        
        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
        <title>{% block title %}Căn tin{% endblock title %}</title>
        <!-- Bootstrap core CSS -->
        <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
        <link href="{% static 'css/font-awesome.min.css'%}" rel="stylesheet">
        <link href="{% static 'css/animsition.min.css' %}" rel="stylesheet">
        <link href="{% static 'css/animate.css' %}" rel="stylesheet">
        <!-- Custom styles for this template -->
        <link href="{% static 'css/style.css' %}" rel="stylesheet"> </head>
        {% block load_static %}

        {% endblock load_static %}

    <body>

        
            
            <!-- Navigation bar-->
            <nav class="navbar navbar-expand-lg navbar-fixed-top navbar-dark bg-dark">
                <a class="navbar-brand" href="{% url 'home' %}" >
                    <img src="{% static 'images/logo.png' %}" width="100" height="50" alt="" loading="lazy">
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item active">
                            <a class="nav-link" href="{% url 'home' %}">Trang chủ <span class="sr-only">(current)</span></a>
                        </li>
                        <li class="nav-item active">
                            <a class="nav-link" href="{% url 'articles:list' %}"> Tin tức <span class="sr-only">(current)</span></a>
                        </li>
                        <li class="nav-item dropdown active">
                            <a class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" >
                            Menu
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="{% url 'food:menu' %}">Tất cả</a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="{% url 'food:bua-sang' %}">Bữa sáng</a>
                                <a class="dropdown-item" href="{% url 'food:bua-trua' %}">Bữa trưa</a>
                                <a class="dropdown-item" href="{% url 'food:bua-toi' %}">Bữa tối</a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="{% url 'food:do-uong' %}">Đồ uống</a>
                                <a class="dropdown-item" href="{% url 'food:an-vat' %}">Ăn vặt</a>
                            </div>
                        </li>
                        
                        <li class="nav-item active">
                            <a class="nav-link" href="{% url 'about' %}"> Giới thiệu <span class="sr-only">(current)</span></a>
                        </li>
                        <li class="nav-item active">
                            <a class="nav-link" href="{% url 'contact' %}"> Liên hệ <span class="sr-only">(current)</span></a>
                        </li>
                    </ul>

                    

                    <div class="collapse navbar-collapse" id="navbarCollapse">
                        <ul class="navbar-nav ml-auto">
                            {% with total_items=cart|length %}
                                {% if total_items > 0 %}
                                    <li class="nav-item">
                                    <a href="{% url "cart:cart_detail" %}" >
                                        Giỏ hàng của bạn có {{ total_items }} món{{ total_items|pluralize }},
                                        {{ cart.get_total_price|floatformat|intcomma }} vnđ
                                    </a>
                                    </li>
                                {% else %}
                                    <a href="{% url "cart:cart_detail" %}">
                                        Giỏ hàng của bạn đang trống.
                                    </a>
                                    </li>
                                {% endif %}
                            {% endwith %}
                        </ul>

                        {% if user.is_authenticated %}
                            <ul class="navbar-nav ml-auto">
                                <li class="nav-item">
                                    <a class="nav-link dropdown-toggle" href="#" id="userMenu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        {{ user.username }}
                                    </a>
                                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userMenu">
                                        <a class="dropdown-item" href="#">Change Information</a>
                                        <a class="dropdown-item" href="{% url 'password_change'%}">Change password</a>
                                        <div class="dropdown-divider"></div>
                                        <a class="dropdown-item" href="{% url 'logout' %}">Log Out</a>
                                    </div>
                                </li>
                            </ul>
                        {% else %}
                            <form class="form-inline ml-auto">
                                <a href="{% url 'login' %}" class="btn btn-outline-secondary">Log In</a>
                                <a href="{% url 'signup' %}" class="btn btn-primary ml-2">Sign up</a>
                            </form>
                        {% endif %}
                    </div>
                    
                </div>
            </nav>
            
            <!-- Content -->

            <div class="container-fluid" style="padding-top: 85px">
                {% block content %}
                {% endblock content %}
            </div>

            <!-- start: FOOTER -->
            <footer class="footer">
                <div class="container">
                    <!-- top footer statrs -->
                    <div class="row top-footer">
                        <div class="col-xs-12 col-sm-3 footer-logo-block color-gray">
                            <a href="#"> <img src="{% static 'images/logo.png' %}" alt="Footer logo"> </a> <span>Order Delivery &amp; Take-Out </span> </div>
                        <div class="col-xs-12 col-sm-2 about color-gray">
                            <h5>Thông tin</h5>
                            <ul>
                                <li><a href="{% url 'about' %}">Giới thiệu chung</a> </li>
                                <li><a href="{% url 'articles:list' %}">Tin tức</a> </li>
                                <li><a href="{% url 'contact' %}">Liên hệ</a> </li>
                                <li><a href="#">Tuyển dụng</a> </li>
                            </ul>
                        </div>
                        <div class="col-xs-12 col-sm-2 how-it-works-links color-gray">
                            <h5>Thực Đơn</h5>
                            <ul>
                                <li><a href="{% url 'food:bua-sang' %}">Bữa sáng</a> </li>
                                <li><a href="{% url 'food:bua-trua' %}">Bữa trưa</a> </li>
                                <li><a href="{% url 'food:bua-toi' %}">Bữa tối</a> </li>
                                <li><a href="{% url 'food:an-vat' %}">Đồ uống</a> </li>
                                <li><a href="{% url 'food:do-uong' %}">Ăn vặt</a> </li>
                            </ul>
                        </div>
                    </div>
                    <!-- top footer ends -->
                    <!-- bottom footer statrs -->
                    <div class="bottom-footer">
                        <div class="row">
                            <div class="col-xs-12 col-sm-3 payment-options color-gray">
                                <h5>Phương thức thanh toán</h5>
                                <ul>
                                    <li>
                                        <a href="#"> <img src="{% static 'images/momo.png' %}" alt="Momo" width="50" height="50"> </a>
                                    </li>
                                    <li>
                                        <a href="#"> <img src="{% static 'images/airpay.jpeg' %}" alt="Airpay" width="50" height="50"> </a>
                                    </li>
                                    <li>
                                        <a href="#"> <img src="{% static 'images/zalopay.png' %}" alt="Maestro" width="50" height="50"> </a>
                                    </li>
                                    <li>
                                        <a href="#"> <img src="{% static 'images/napas.png' %}" alt="Stripe" width="50" height="50"> </a>
                                    </li>
                                </ul>
                            </div>
                            <div class="col-xs-12 col-sm-4 address color-gray">
                                <h5>Địa chỉ</h5>
                                <p>Căn tin UIT, khu phố 6, phường Linh Trung, quận Thủ Đức, Tp. Hồ Chí Minh</p>
                                <h5>Phone: <a href="tel:+08123456123">08 123456 123</a></h5> </div>
                        </div>
                    </div>
                    <!-- bottom footer ends -->
                </div>
            </footer>
            <!-- end:Footer -->
        </div>


            <!-- jQuery first, then Popper.js, then Bootstrap JS -->
            
            <script src="{% static 'js/jquery.min.js' %}"></script>
            <script src="{% static 'js/tether.min.js' %}"></script>
            <script src="{% static 'js/bootstrap.min.js' %}"></script>
            <script src="{% static 'js/animsition.min.js' %}"></script>
            <script src="{% static 'js/bootstrap-slider.min.js' %}"></script>
            <script src="{% static 'js/jquery.isotope.min.js' %}"></script>
            <script src="{% static 'js/headroom.js' %}"></script>
            <script src="{% static 'js/foodpicky.min.js' %}"></script>

    </body>
</html>